[G2M] contributors stats revisions
EQWorks/release pull request #52
Opened 2022-01-26 21:57 UTC by woozyking

- upgrade eslint from v6 to v8, and its config
- revise contributions/contributors by-commit filter logic against known `base...head` commit hashes instead of the previous hash slicing strategy
- introduce an `--include-contributors` flag and its default and behaviour depends on the availability of the presence of the `GITHUB_TOKEN` environment variable
- add `yarn local` for local test convenience

2022-01-26 22:00 UTC, woozyking commented
before the filter revision, if we run `env $(print-env) node index.js notes --print --skip alpha` we'd get:

```md
# Release Notes (by category): from v3.3.1 to v3.4.0

## version

[CHANGED] bump v3.4.0 (4e5999a by [Runzhou Li (woozyking)](https://github.com/woozyking))
[CHANGED] bump v3.4.0-alpha.0 (bad3923 by [Runzhou Li (woozyking)](https://github.com/woozyking))


## devops

[CHANGED] run commit-watch only on PRs (3259daa by [Runzhou Li (woozyking)](https://github.com/woozyking))
[CHANGED] dev env to node 14, add commit-watch in master CI workflow (f7e60f3 by [Runzhou Li (woozyking)](https://github.com/woozyking))

- yarn upgrade-interactive 20210525

 ### deps
[CHANGED] yarn upgrade-interactive 20210223 (4711079 by [Runzhou Li (woozyking)](https://github.com/woozyking))


## added

[ADDED] add a correction case from firstorder (19f5d03 by [Runzhou Li (Leo)](https://github.com/woozyking))


## lib

[CHANGED] parseRaw returns t1/t2 categories too (4406400 by [Runzhou Li (woozyking)](https://github.com/woozyking))
[ADDED] add new parseRaw for NLP labeling of arbitrary array of strings (1f91013 by [Runzhou Li (woozyking)](https://github.com/woozyking))


## nlp

 ### labels
[CHANGED] new changed case from #36 (f031019 by [Runzhou Li (Leo)](https://github.com/woozyking))
[ADDED] new added case from #36 (8b10ef6 by [Runzhou Li (Leo)](https://github.com/woozyking))

 ### label
[ADDED] add label training data from Snoke v1.4.34[squash] (17ae7a0 by Tamires Lowande)
[ADDED] add label training data 2021-02-01 (bc9ce2b by Runzhou Li (Leo))


# Contributors: 

- [**vxsl**](https://github.com/vxsl) (🎉 fresh contributor, 6 commits)
- [**woozyking**](https://github.com/woozyking) (22 commits)
```

note the contributors are actually detached from actual commits that the `base...head` git diff pertains to.

comparatively, after the filter revision (same invocation: `env $(print-env) node index.js notes --print --skip alpha`):

```md
# Release Notes (by category): from v3.3.1 to v3.4.0

## version

[CHANGED] bump v3.4.0 (4e5999a by [Runzhou Li (woozyking)](https://github.com/woozyking))
[CHANGED] bump v3.4.0-alpha.0 (bad3923 by [Runzhou Li (woozyking)](https://github.com/woozyking))


## devops

[CHANGED] run commit-watch only on PRs (3259daa by [Runzhou Li (woozyking)](https://github.com/woozyking))
[CHANGED] dev env to node 14, add commit-watch in master CI workflow (f7e60f3 by [Runzhou Li (woozyking)](https://github.com/woozyking))

- yarn upgrade-interactive 20210525

 ### deps
[CHANGED] yarn upgrade-interactive 20210223 (4711079 by [Runzhou Li (woozyking)](https://github.com/woozyking))


## added

[ADDED] add a correction case from firstorder (19f5d03 by [Runzhou Li (Leo)](https://github.com/woozyking))


## lib

[CHANGED] parseRaw returns t1/t2 categories too (4406400 by [Runzhou Li (woozyking)](https://github.com/woozyking))
[ADDED] add new parseRaw for NLP labeling of arbitrary array of strings (1f91013 by [Runzhou Li (woozyking)](https://github.com/woozyking))


## nlp

 ### labels
[CHANGED] new changed case from #36 (f031019 by [Runzhou Li (Leo)](https://github.com/woozyking))
[ADDED] new added case from #36 (8b10ef6 by [Runzhou Li (Leo)](https://github.com/woozyking))

 ### label
[ADDED] add label training data from Snoke v1.4.34[squash] (17ae7a0 by [Tamires Lowande](https://github.com/tlowande))
[ADDED] add label training data 2021-02-01 (bc9ce2b by [Runzhou Li (Leo)](https://github.com/woozyking))


# Contributors: 

- [**woozyking**](https://github.com/woozyking) (11 commits)
- [**tlowande**](https://github.com/tlowande) (1 commits)
```

2022-01-26 22:20 UTC, woozyking commented
published as `v3.5.0-alpha.1`

2022-01-27 00:46 UTC, hyx131 approved these changes

2022-01-28 14:03 UTC, vxsl requested changes
lgtm but it looks like incorrect contributor data is provided for releases that are ahead of the main branch. Suggested a fix

2022-01-28 16:52 UTC, vxsl approved these changes

2022-01-28 16:59 UTC, merged